site_name: Engineering Handbook - The National Archives
site_url: https://nationalarchives.github.io/engineering-handbook/
repo_url: https://github.com/nationalarchives/engineering-handbook
dev_addr: localhost:8888
use_directory_urls: true
nav:
  - Home:
    - index.md
    - Get started:
      - get-started/index.md
      - Tools: get-started/tools.md
      - Services: get-started/services.md
      - Communication: get-started/communication.md
    - Organisation:
      - organisation/index.md
      - Technical Architects Group: organisation/technical-architects-group.md
      - Technical Governance Board: organisation/technical-governance-board.md
  - Technology:
    - technology/index.md
    - HTML: technology/frontend/html.md
    - JavaScript: technology/frontend/javascript.md
    - CSS: technology/frontend/css.md
    - Python: technology/backend/python.md
    # - Scala: technology/backend/scala.md
    - Postgres: technology/database/postgres.md
    - Infrastructure:
      - Amazon Web Services (AWS): technology/infrastructure/aws.md
      - Containers: technology/infrastructure/containers.md
      - Terraform: technology/infrastructure/terraform.md
      - Nginx: technology/infrastructure/nginx.md
    - Standards:
      - Accessibility: technology/standards/accessibility.md
      - APIs: technology/standards/api.md
      - Browser support: technology/standards/browser-support.md
      - Licences: technology/standards/licences.md
      - Security: technology/standards/security.md
      - Testing: technology/standards/testing.md
      - URLs: technology/standards/url.md
  - Ways of working:
    - ways-of-working/index.md
    - Service standard: ways-of-working/service-standard.md
    - Progressive enhancement: ways-of-working/progressive-enhancement.md
    - Version control: ways-of-working/version-control.md
    - Documentation: ways-of-working/documentation.md
    - Deployment: ways-of-working/deployment.md
    - Definition of done: ways-of-working/definition-of-done.md
  - Third party:
    - third-party/index.md
    - NPMJS: third-party/npmjs.md
    - PyPI: third-party/pypi.md
    - CDNs: third-party/cdn.md
    - GitHub: third-party/github.md
    - Docker registries: third-party/docker-registries.md
    - Analytics: third-party/analytics.md
    - YouTube: third-party/youtube.md
  - Resources:
    - resources/index.md
    - TNA Frontend: resources/tna-frontend.md
    - TNA Frontend Jinja: resources/tna-frontend-jinja.md
    # - TNA Frontend Django: resources/tna-frontend-django.md
    - Design System: resources/design-system.md
    - Docker images: resources/docker-images.md
    - Application templates: resources/application-templates.md
    - GOV.UK Prototype Kit: resources/govuk-prototype-kit.md
theme:
  name: material
  custom_dir: overrides
  favicon: https://raw.githubusercontent.com/nationalarchives/tna-frontend/main/src/nationalarchives/assets/images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
  palette:
    - primary: custom
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - inline-select-svg
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
